import {
  AnswerLengthDto,
  AnswerSchema,
  AnswerSource,
  GenerationScope,
  GenerationDifficulty,
} from './dto/create-question.dto.js';

// ── Gemini response types ──────────────────────────────────────────────────

export interface MCQChoiceRaw {
  choice_text: string;
  choice_order: number;
  is_correct: boolean;
}

export interface GradingKeywordRaw {
  keyword: string;
  weight: number;
  is_required: boolean;
}

export interface SourceCitationRaw {
  resourceId: number;
  fileName: string;
  page: number | null;
  snippet: string;
}

export interface QuestionRaw {
  title: string;
  question_type: 'mcq' | 'open_ended';
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
  answer_source: 'file' | 'ai';
  explanation?: string;
  choices?: MCQChoiceRaw[];
  sample_answer?: string;
  grading_keywords?: GradingKeywordRaw[];
  source_citation?: SourceCitationRaw | null;
}

export interface GeneratedQuestionsResponse {
  error?: string;
  questions: QuestionRaw[];
}

// ── Shared JSON schema string ──────────────────────────────────────────────

const JSON_SCHEMA = `{
  "questions": [
    {
      "title": "Question text",
      "question_type": "mcq",
      "difficulty": "EASY" | "MEDIUM" | "HARD",
      "answer_source": "file" | "ai",
      "explanation": "Brief explanation of why the answer is correct",
      "source_citation": { "resourceId": 1, "fileName": "lecture.pdf", "page": 3, "snippet": "Copy-paste exact HTML substring from the document — no tag changes" } | null,
      "choices": [
        { "choice_text": "Option A", "choice_order": 1, "is_correct": false },
        { "choice_text": "Option B", "choice_order": 2, "is_correct": true },
        { "choice_text": "Option C", "choice_order": 3, "is_correct": false },
        { "choice_text": "Option D", "choice_order": 4, "is_correct": false }
      ]
    },
    {
      "title": "Question text",
      "question_type": "open_ended",
      "difficulty": "EASY" | "MEDIUM" | "HARD",
      "answer_source": "file" | "ai",
      "explanation": "Key concepts the answer should cover",
      "source_citation": { "resourceId": 1, "fileName": "lecture.pdf", "page": 3, "snippet": "Copy-paste exact HTML substring from the document — no tag changes" } | null,
      "sample_answer": "A well-structured sample answer",
      "grading_keywords": [
        { "keyword": "key concept", "weight": 1.0, "is_required": true },
        { "keyword": "supporting idea", "weight": 0.5, "is_required": false }
      ]
    }
  ]
}`;

// ── Prompt builders ────────────────────────────────────────────────────────

export function buildAutoPrompt(dto: {
  answerSchema: AnswerSchema;
  difficulty: GenerationDifficulty;
  generationScope: GenerationScope;
  answerSource: AnswerSource;
  count?: number;
  minWords: number;
  answerLength?: AnswerLengthDto;
  resourceMeta?: { id: number; fileName: string }[];
}): string {
  const {
    answerSchema,
    difficulty,
    generationScope,
    answerSource,
    count,
    minWords,
    answerLength,
    resourceMeta,
  } = dto;

  const questionTypeInstruction =
    answerSchema === AnswerSchema.MCQ
      ? 'All questions must be of type "mcq". Each MCQ must have exactly 4 choices with exactly one marked is_correct: true.'
      : answerSchema === AnswerSchema.OPEN_ENDED
        ? 'All questions must be of type "open_ended". Each open-ended question must have a sample_answer and at least 3 grading_keywords.'
        : 'Generate a mix of "mcq" and "open_ended" questions. MCQs must have exactly 4 choices with exactly one correct. Open-ended questions must have a sample_answer and at least 3 grading_keywords.';

  const difficultyInstruction =
    difficulty === GenerationDifficulty.MIXED
      ? 'Use a balanced mix of EASY, MEDIUM, and HARD difficulties across the questions.'
      : `All questions must have difficulty "${difficulty}".`;

  const countInstruction =
    generationScope === GenerationScope.FIXED
      ? `Generate exactly ${count} questions.`
      : 'Generate as many high-quality, non-redundant questions as the material supports (aim for comprehensive coverage of all topics).';

  const answerSourceInstruction =
    answerSource === AnswerSource.FILE
      ? 'ANSWER SOURCE — FILE (VERBATIM): The correct answer (for MCQ: the is_correct choice; for open_ended: the sample_answer) must be exact verbatim words from the provided file content — do not paraphrase or rephrase. A user must be able to find the correct answer by Ctrl+F searching the exact text in the source document. For MCQ, the three incorrect distractors must be generated by AI (plausible but wrong). For open_ended, grading_keywords and explanation may be written by AI.'
      : answerSource === AnswerSource.MIXED
        ? 'ANSWER SOURCE — MIXED: Use verbatim text from the files for question titles and correct answers where possible, but freely use your broader knowledge to write explanations, enrich sample answers, and craft MCQ distractors.'
        : 'ANSWER SOURCE — AI: Use the provided files as the primary source for topics and questions, but you may use your broader knowledge to write clear explanations, well-phrased distractors, and comprehensive sample answers beyond what is literally stated in the files.';

  const resourceList =
    resourceMeta && resourceMeta.length > 0
      ? resourceMeta
          .map((r) => `  - id: ${r.id}, fileName: "${r.fileName}"`)
          .join('\n')
      : '  (none)';

  return `You are an expert educational content creator. Analyze the provided study material(s) and generate exam/quiz questions based on their content.

PRE-CHECK: Before generating, estimate the total word count of the provided material. If it contains fewer than ${minWords} words, return { "error": "INSUFFICIENT_CONTENT", "questions": [] } and stop.

Available source documents:
${resourceList}

INSTRUCTIONS:
1. ${countInstruction}
2. ${questionTypeInstruction}
3. ${difficultyInstruction}
4. ${answerSourceInstruction}
5. Avoid duplicate or very similar questions.
6. For MCQ: only one choice must have is_correct: true; the other three must be plausible distractors.
7. For open_ended: ${answerLength ? `sample_answer should be approximately ${answerLength.amount} ${answerLength.unit} long` : 'sample_answer should be 2–5 sentences'}; grading_keywords should reflect the most important concepts needed in a correct answer.
8. The "explanation" field is mandatory for all questions.
9. Set answer_source to "file" if the correct answer / sample answer was taken verbatim or near-verbatim from the document, or "ai" if you used your own knowledge to write or significantly rephrase it.
10. source_citation: If answer_source is "file", populate source_citation with { "resourceId": <id from the list above>, "fileName": "<fileName>", "page": <page number or null>, "snippet": "<copy-paste the exact HTML substring from the document as-is>" }. CRITICAL for snippet: the document is raw HTML. Find the smallest block element that contains the answer (e.g. a <p>, <li>, <h2>, <td>) and copy its full opening tag, all inner content, and closing tag exactly as they appear in the raw HTML — character-for-character. Rules: (1) Copy the entire element from its opening tag to its closing tag — do NOT omit, skip, or truncate any part of its content. (2) The snippet must be one contiguous copy — do NOT merge non-adjacent portions or jump over text in the middle. (3) Do NOT use ellipsis ("..." or "…") anywhere. (4) Parentheses "()" in the source are literal text characters — do NOT treat them as a cue to summarize or skip. (5) Do NOT reconstruct or wrap the element in a new parent (e.g. never wrap a <li> inside a new <ul>/<ol> — copy just the <li>…</li> itself). (6) Do NOT strip, add, or modify any HTML tags or attributes. The snippet must be a verbatim substring of the raw HTML such that indexOf(snippet) > -1 on the source HTML string. If answer_source is "ai", set source_citation to null.

OUTPUT FORMAT:
Return ONLY raw JSON — no markdown, no code fences, no extra text before or after. The JSON must strictly follow this schema:

${JSON_SCHEMA}`;
}

export function buildRegeneratePrompt(dto: {
  regenerateFromScratch: boolean;
  originalTitle: string;
  questionType: 'mcq' | 'open_ended';
  difficulty: string;
  answerSource: AnswerSource;
  resourceMeta?: { id: number; fileName: string }[];
}): string {
  const {
    regenerateFromScratch,
    originalTitle,
    questionType,
    difficulty,
    answerSource,
    resourceMeta,
  } = dto;

  const scopeInstruction = regenerateFromScratch
    ? `Generate a COMPLETELY NEW question on the same general subject area covered in the source material. The new question must have a different title, angle, and content from: "${originalTitle}".`
    : `Keep the same question title exactly as-is: "${originalTitle}". Only regenerate the answer, choices, explanation, and related fields.`;

  const typeInstruction =
    questionType === 'mcq'
      ? 'The question must be of type "mcq" with exactly 4 choices, one marked is_correct: true.'
      : 'The question must be of type "open_ended" with a sample_answer and at least 3 grading_keywords.';

  const answerSourceInstruction =
    answerSource === AnswerSource.FILE
      ? 'ANSWER SOURCE — FILE (VERBATIM): The correct answer (for MCQ: the is_correct choice; for open_ended: the sample_answer) must be exact verbatim words from the provided file content — do not paraphrase. For MCQ, the three incorrect distractors must be generated by AI. For open_ended, grading_keywords and explanation may be written by AI.'
      : answerSource === AnswerSource.MIXED
        ? 'ANSWER SOURCE — MIXED: Use verbatim text from the files for correct answers where possible, but freely use your broader knowledge for explanations, sample answers, and distractors.'
        : 'ANSWER SOURCE — AI: Use the files as the topic source but write clear explanations, well-phrased distractors, and comprehensive sample answers using your broader knowledge.';

  const resourceList =
    resourceMeta && resourceMeta.length > 0
      ? resourceMeta
          .map((r) => `  - id: ${r.id}, fileName: "${r.fileName}"`)
          .join('\n')
      : '  (none)';

  const sourceCitationField = `"source_citation": { "resourceId": 1, "fileName": "lecture.pdf", "page": 3, "snippet": "Copy-paste exact HTML substring from the document — no tag changes" } | null`;

  const singleQuestionSchema =
    questionType === 'mcq'
      ? `{
  "questions": [
    {
      "title": "Question text",
      "question_type": "mcq",
      "difficulty": "${difficulty}",
      "answer_source": "file" | "ai",
      "explanation": "Brief explanation of why the answer is correct",
      ${sourceCitationField},
      "choices": [
        { "choice_text": "Option A", "choice_order": 1, "is_correct": false },
        { "choice_text": "Option B", "choice_order": 2, "is_correct": true },
        { "choice_text": "Option C", "choice_order": 3, "is_correct": false },
        { "choice_text": "Option D", "choice_order": 4, "is_correct": false }
      ]
    }
  ]
}`
      : `{
  "questions": [
    {
      "title": "Question text",
      "question_type": "open_ended",
      "difficulty": "${difficulty}",
      "answer_source": "file" | "ai",
      "explanation": "Key concepts the answer should cover",
      ${sourceCitationField},
      "sample_answer": "A well-structured sample answer",
      "grading_keywords": [
        { "keyword": "key concept", "weight": 1.0, "is_required": true },
        { "keyword": "supporting idea", "weight": 0.5, "is_required": false }
      ]
    }
  ]
}`;

  return `You are an expert educational content creator. Regenerate a single question based on the provided study material.

Available source documents:
${resourceList}

INSTRUCTIONS:
1. ${scopeInstruction}
2. ${typeInstruction}
3. The question difficulty must be "${difficulty}".
4. ${answerSourceInstruction}
5. The "explanation" field is mandatory.
6. Set answer_source to "file" if the correct answer was taken verbatim from the document, or "ai" if you used your own knowledge.
7. source_citation: If answer_source is "file", populate source_citation with { "resourceId": <id from list>, "fileName": "<fileName>", "page": <page or null>, "snippet": "<copy-paste the exact HTML substring from the document as-is>" }. CRITICAL for snippet: treat the HTML document as a plain string and copy-paste the relevant portion character-for-character. Do NOT add extra tags (e.g. <p>, <span>), do NOT remove existing tags, do NOT reformat or pretty-print the HTML. The snippet must be a literal substring of the source HTML. If answer_source is "ai", set source_citation to null.

OUTPUT FORMAT:
Return ONLY raw JSON — no markdown, no code fences, no extra text. The JSON must strictly follow this schema:

${singleQuestionSchema}`;
}

export function buildManualPrompt(
  rawQuestions: string,
  answerSource: AnswerSource,
  resourceMeta?: { id: number; fileName: string }[],
): string {
  const answerSourceInstruction =
    answerSource === AnswerSource.FILE
      ? 'ANSWER SOURCE — FILE (VERBATIM): The correct answer (for MCQ: the is_correct choice; for open_ended: the sample_answer) must be exact verbatim words from the provided file content — do not paraphrase or rephrase. A user must be able to find the correct answer by Ctrl+F searching the exact text in the source document. For MCQ, the three incorrect distractors must be generated by AI (plausible but wrong). For open_ended, grading_keywords and explanation may be written by AI.'
      : answerSource === AnswerSource.MIXED
        ? 'ANSWER SOURCE — MIXED: Use verbatim text from the files for question titles and correct answers where possible, but freely use your broader knowledge to write explanations, enrich sample answers, and craft MCQ distractors.'
        : 'ANSWER SOURCE — AI: You may use your broader knowledge to enrich explanations, sample answers, and distractors beyond what is literally in the files.';

  const resourceList =
    resourceMeta && resourceMeta.length > 0
      ? resourceMeta
          .map((r) => `  - id: ${r.id}, fileName: "${r.fileName}"`)
          .join('\n')
      : '  (none)';

  return `You are an expert educational content formatter. The user has written the following questions in free-form text. Your job is to parse them and structure each question into the exact JSON schema below.

Available source documents:
${resourceList}

Rules:
- If a question has multiple-choice options, set question_type to "mcq" and populate choices (exactly 4, one correct).
- If a question is open-ended (no choices), set question_type to "open_ended" and provide a sample_answer plus at least 3 grading_keywords.
- Infer a difficulty (EASY, MEDIUM, or HARD) for each question based on its complexity.
- Write a concise explanation for each question.
- Do not add or remove questions — structure exactly what the user provided.
- ${answerSourceInstruction}
- Set answer_source to "file" if the correct answer / sample answer was taken verbatim or near-verbatim from the document, or "ai" if you used your own knowledge to write or significantly rephrase it.
- source_citation: If answer_source is "file", populate source_citation with { "resourceId": <id from list>, "fileName": "<fileName>", "page": <page or null>, "snippet": "<copy-paste the exact HTML substring from the document as-is>" }. CRITICAL for snippet: treat the HTML document as a plain string and copy-paste the relevant portion character-for-character. Do NOT add extra tags (e.g. <p>, <span>), do NOT remove existing tags, do NOT reformat or pretty-print the HTML. The snippet must be a literal substring of the source HTML. If answer_source is "ai", set source_citation to null.

OUTPUT FORMAT:
Return ONLY raw JSON — no markdown, no code fences, no extra text. Follow this schema exactly:

${JSON_SCHEMA}

USER-PROVIDED QUESTIONS:
${rawQuestions}`;
}
